import subprocess
import time
import os
import shutil

log_path = r"c:\Users\a518028\OneDrive - Volvo Group\repos\learner\chrome_startup.log"
chrome_path = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
user_data_dir = r"C:\Users\a518028\.gemini\antigravity\chrome-debug"
default_user_dir = r"C:\Users\a518028\AppData\Local\Google\Chrome\User Data"

# Ensure target directories exist
os.makedirs(user_data_dir, exist_ok=True)
os.makedirs(default_user_dir, exist_ok=True)

# Remove any old DevToolsActivePort files to avoid stale port reading
for target in [user_data_dir, default_user_dir]:
    p = os.path.join(target, "DevToolsActivePort")
    if os.path.exists(p):
        try:
            os.remove(p)
        except Exception as e:
            print(f"Could not remove old port file at {p}: {e}")

print(f"Starting Chrome from {chrome_path} with dynamic debugging port...")
with open(log_path, "w") as log_file:
    try:
        proc = subprocess.Popen(
            [chrome_path, "--remote-debugging-port=0", "--headless", "--disable-gpu", f"--user-data-dir={user_data_dir}"],
            stdout=log_file,
            stderr=log_file,
            text=True
        )
        print(f"Chrome started with PID: {proc.pid}")
        
        # Wait for DevToolsActivePort to be created
        src_port_file = os.path.join(user_data_dir, "DevToolsActivePort")
        dest_port_file = os.path.join(default_user_dir, "DevToolsActivePort")
        
        found = False
        for _ in range(40):
            if os.path.exists(src_port_file):
                found = True
                break
            time.sleep(0.5)
            
        if found:
            print(f"Found DevToolsActivePort at {src_port_file}. Copying to {dest_port_file}...")
            shutil.copy2(src_port_file, dest_port_file)
            print("Copied successfully.")
            
            # Keep monitoring and syncing the file
            while proc.poll() is None:
                if os.path.exists(src_port_file):
                    try:
                        shutil.copy2(src_port_file, dest_port_file)
                    except Exception as e:
                        pass
                time.sleep(1)
        else:
            print("Timed out waiting for DevToolsActivePort to be generated by Chrome.")
            ret = proc.poll()
            if ret is not None:
                print(f"Chrome exited prematurely with return code: {ret}")
    except Exception as e:
        print(f"Error: {e}")
